base: 'https://ddev-slub-katalog.ddev.site/'
baseVariants: {  }
errorHandling: {  }
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: ''
    hreflang: de-DE
    direction: ltr
    flag: de
    languageId: '0'
    solr_core_read: core_de
  -
    title: English
    enabled: true
    base: /en/
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: ''
    hreflang: en-US
    direction: ltr
    fallbackType: strict
    fallbacks: '0'
    flag: en-us-gb
    languageId: '1'
    solr_core_read: core_en
rootPageId: 1
routes: {  }
solr_enabled_read: true
solr_host_read: ddev-slub-katalog.ddev.site
solr_path_read: /solr/
solr_port_read: '8985'
solr_scheme_read: http
solr_use_write_connection: false
